apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-app
  namespace: argocd
spec:
  source:
    path: infra/cert-manager
    repoURL: 'https://github.com/Ion-manden/gitop-data.git'
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    name: ''
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-helm
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.12.1
    helm:
      parameters:
      - name: "installCRDs"
        value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
