apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  namespace: grafana
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: root
      admin_password: secret
