apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda-app
  namespace: argocd
spec:
  source:
    path: infra/redpanda
    repoURL: 'https://github.com/Ion-manden/gitops-data.git'
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    name: ''
    namespace: redpanda
    server: 'https://kubernetes.default.svc'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda-helm
  namespace: argocd
spec:
  project: default
  source:
    chart: redpanda-operator
    repoURL: https://charts.vectorized.io
    targetRevision: v23.1.11
    # helm:
    #   releaseName: redpanda-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: redpanda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/redpanda-data/redpanda'
    path: src/go/k8s/config/crd/
    targetRevision: v23.1.11
  destination:
    server: "https://kubernetes.default.svc"
    namespace: redpanda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
