apiVersion: v1
kind: ConfigMap
metadata:
  name: console-config
  namespace: redpanda
data:
  config: |
    kafka:
      brokers: ["redpanda-cluster.redpanda.svc.cluster.local:9092"]
      schemaRegistry:
        enabled: true
        urls: ["http://redpanda-cluster-cluster.redpanda.svc.cluster.local:8081"]
    redpanda:
      adminApi:
        enabled: true
        urls: ["http://redpanda-cluster.redpanda.svc.cluster.local:9644"]
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-console-service
  namespace: redpanda
spec:
  selector:
    app: redpanda-console
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console-deployment
  namespace: redpanda
  labels:
    app: redpanda-console

spec:
  replicas: 3
  selector:
    matchLabels:
      app: redpanda-console

  template:
    metadata:
      labels:
        app: redpanda-console

    spec:
      containers:
      - name: console
        image: docker.redpanda.com/redpandadata/console:v2.2.4
        ports:
        - containerPort: 8080
        env:
          - name: CONFIG_FILEPATH
            value: "/tmp/config.yml"
        volumeMounts:
          - name: config
            mountPath: /tmp/config.yml
            subPath: config

      volumes:
      - name: config
        configMap:
          name: console-config
